name: Build & Deploy TestFlight iOS

on:
  # Triggers the workflow on push events for release/ branches
  push:
    branches:
       - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  echo_build:
    name: print
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: echo "GITHUB_RUN_NUMBER $GITHUB_RUN_NUMBER"
