name: Sample workflow

on:
  push:
    branches:
      - '**'
      - '!main'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  echo_build:
    name: print
    runs-on: self-hosted
    steps:
      - name: Check for EXPO_TOKEN
        run: echo "Running on release published- GITHUB_RUN_NUMBER $GITHUB_RUN_NUMBER. GITHUB_RUN_ATTEMPT $GITHUB_RUN_ATTEMPT!"
      - name: test nw
        run: curl -o - -I https://apply-api.missionlane-dev.com/api/v2/flow/offer/invite-code/MLSCLBO0005
        shell: bash
