name: Build & Deploy TestFlight iOS

on:
  # Triggers the workflow on push events for release/ branches
  push:
    branches:
       - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  echo_build:
    name: print
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: echo "Build Number $GITHUB_RUN_NUMBER"
