name: Build & Deploy TestFlight iOS

on:
  release:
    types: published


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  echo_build:
    name: print
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: echo "Running on release published- GITHUB_RUN_NUMBER $GITHUB_RUN_NUMBER. GITHUB_RUN_ATTEMPT $GITHUB_RUN_ATTEMPT!"
